### ISSUE TITLE
PCA_moco missing 'datafile' arg?

### ISSUE THREAD

**Issue by bellabrez** [ClandininLab/brainsss2#32]
In preprocess.py when the workflow_dics are getting built I don't see how 'PCA_moco' gets 'datafile'? It is directly defined here for 'PCA_resid'. It is not in the settins.json and I don't see how dimensionality_reduction.py would resolve not having that arg.

**Comment by poldrack** [comment]
a default is specified in brainsss2.argparse_utils.add_dr_args:

```
parser.add_argument('--datafile', type=str,
        default='preproc/functional_channel_2_moco_smooth-2.0mu.h5',
        help='func data file subpath (defaults to  preproc/functional_channel_2_moco_smooth-2.0mu.h5')
```
